apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
spec:
  containers:
    - name: ez-docker-helm-build
      image: ezezeasy/ez-docker-helm-build:1.41
      command: ["sleep"]
      args: ["infinity"]
      imagePullPolicy: Always
      securityContext:
        privileged: true
        runAsUser: 0

    - name: python-test
      image: maximusmaxi/tests
      command: ["sleep"]
      args: ["infinity"]
      imagePullPolicy: Always
      securityContext:
        privileged: false

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket