FROM python:3.8-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./license-registry.py .
COPY logging_config.py logging_config.py
CMD ["python", "license-registry.py"]