apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  labels:
    app: orchestrator
spec:
  replicas: {{ .Values.orchestrator.replicaCount }}
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: maximusmaxi/orchestrator
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /app/logs
          name: orchestrator-logs
      volumes:
      - name: orchestrator-logs
        persistentVolumeClaim:
          claimName: orchestrator-pvc
